[package]
name = "ps5-dump-forge-gui"
description = "PS5 game image converter (GUI)"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[[bin]]
name = "Forge"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
ps5-dump-forge-core.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
